fixed
pH-7/Simple-Java-Text-Editor pull request #17
Opened 2017-10-08 09:58 UTC by LordStephen77

2017-10-08 10:02 UTC, LordStephen77 commented
Travis is configured badly I think. Travis and Gradle are a bunch of problems ;) A greeting

2017-10-08 17:29 UTC, pH-7 requested changes

2017-10-08 17:29 UTC, pH-7 commented on src/simplejavatexteditor/SupportedKeywords.java
> +    private String[] supportedLanguage = {".cpp",".java"};
Thanks for fixing the typo! You could also change it to plural to be `supportedLanguages` to be clearer.

2017-10-08 17:29 UTC, pH-7 commented on src/simplejavatexteditor/SupportedKeywords.java
> +    public String[] getsupportedLanguage() {
As long as you are here, you could also change its name to be plural ;)
`public String[] getsupportedLanguages() {`

2017-10-11 05:53 UTC, pH-7 commented
@LordStephen77 Let me know if you had the change to see my comments above  ;)

2017-10-18 16:33 UTC, pH-7 commented on src/simplejavatexteditor/SupportedKeywords.java
> +    private String[] supportedLanguage = {".cpp",".java"};
@LordStephen77 Did you get a chance to look at my comment?

2017-10-18 16:34 UTC, pH-7 commented on src/simplejavatexteditor/SupportedKeywords.java
> +    public String[] getsupportedLanguage() {
@LordStephen77 Did you get a chance to look at my comment

2017-10-22 18:00 UTC, pH-7 commented
Because I didn't get any answers from you, I have to close this one in order to keep the workflow cleanned.

2017-10-22 18:00 UTC, closed without merging

2017-10-22 18:01 UTC, pH-7 commented on .gitignore
> +/bin/
I think this one isn't necessary. Could be removed ;)