#Bug, No check on open file option to save changes.
pH-7/Simple-Java-Text-Editor pull request #27
Opened 2018-10-13 13:07 UTC by laiqujan

Fixed.
Hi,
First of all, I really appreciate your work towards open source community.
I really wants to contribute in this project So, I started to test Text-editor and found some bug that there is no check on open file option to save changes if there is text in notepad.
can you please approve my pull request or  add fallowing lines of code in your UI.java  class for open file option.
// If the source was the "open" option

2018-10-19 20:13 UTC, pH-7 commented
Hey @laiqujan Thanks very much for your PR. I really appreciate it!
I see that there is a conflict there with some newer changes done in `src/simplejavatexteditor/UI.java` Can you fix it?

2018-10-19 20:26 UTC, pH-7 requested changes

2018-10-19 20:26 UTC, pH-7 commented on .gitignore
> +/bin/
I think, we don't really need this. It depends on your own environment, but no need to commit it.
If you can revert it, that would be great.

2018-10-19 20:26 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +                int n = JOptionPane.showOptionDialog(this, "Do you want to save changes ?", "Question",
Maybe `Do you want to save the changes?` instead (and remove also the space before the question mark). I know that this isn't you (my bad :)), but since you modified the text, you can do this too.

2018-10-19 20:26 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I'm sure you like DRY principle. However, you duplicated the same code as above https://github.com/pH-7/Simple-Java-Text-Editor/pull/27/files#diff-444b0d2f64a93f3dbc07fc4e0eb73f6dR473

Could you avoid doing this. Same for `Object[] options = {"Save", "No Save", "Return"};` array, `JOptionPane.YES_NO_CANCEL_OPTION, ...`, ..., etc.

This block should be refactoring instead.

2018-10-19 20:26 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +    private void openFile(){
Nice addition. I like it 😃

2018-10-19 22:17 UTC, laiqujan commented
Thank-you @pH-7  for your kind response i resolved the conflict, let me know if any thing else creates problem.

2018-10-20 20:12 UTC, pH-7 commented
Great! Yes, there are also my above comments https://github.com/pH-7/Simple-Java-Text-Editor/pull/27#pullrequestreview-166680145 (check it directly on Github, it will be easier)

2018-10-22 02:16 UTC, pH-7 commented on .gitignore
> -/bin/
Oh, I was only speaking about the one you added (`/bin/`). Not the ones above.

2018-10-22 02:17 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-10-22 02:21 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-10-22 02:22 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-10-22 02:23 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-10-22 02:26 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-10-22 02:26 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +        	  if (edit) {
I again @laiqujan I think you didn't read my comment or forgot it :)

2018-11-14 04:30 UTC, pH-7 commented
@laiqujan Closing it until you fixed the mentioned issues. Please reopen it once done.

2018-11-14 04:30 UTC, closed without merging