improvements
pH-7/Simple-Java-Text-Editor pull request #43
Opened 2022-06-05 06:44 UTC by frangametv

2022-06-05 07:47 UTC, pH-7 commented
Thanks very much for your contribution @frangametv 

Could you describe what your PR does and add some screenshots of the text editor after your changes?

2022-06-06 12:49 UTC, frangametv commented
I moved the "icons" folder inside the .jar and used class resource loading; then i forced the JavaAWT UIManager Style to Windows Modern Look, and this gives a completely new modern look to the notepad.
You have the code, I only changed a few lines and I also recompiled the project into a .jar, you can see the differences by yourself.

2022-06-19 09:20 UTC, pH-7 requested changes
👍 Just two minor changes needed to be confirmed/changed.

2022-06-19 09:20 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> - * @name        Simple Java NotePad
Could you put back this comment please?

2022-06-19 09:20 UTC, pH-7 commented on .classpath
> -	<classpathentry kind="src" path="icons"/>
Was this redundant?

2022-06-19 09:22 UTC, pH-7 commented
@frangametv With what Java version did you test it?

@frangametv Could you also update the `SimpleJavaTextEditor.jar` with your version and run it? 
You can also generate easily a new jar file with the following command when you are in src/ directory `jar cmvf ../manifest.mf ../SimpleJavaTextEditor.jar simplejavatexteditor/*.class`

2022-06-20 09:52 UTC, frangametv commented on .classpath
> -	<classpathentry kind="src" path="icons"/>
Yes

2022-06-20 10:20 UTC, frangametv commented
**Java version:** From 1.8 to the newest, it worked just fine
I already updated the Jar file, as you can see from the changes.

2022-06-20 10:21 UTC, frangametv commented
Sorry for the deleted comment, my bad

2022-06-20 22:35 UTC, pH-7 commented
> **Java version:** From 1.8 to the newest, it worked just fine
> I already updated the Jar file, as you can see from the changes.

Beautiful! This sounds brilliant @frangametv! I will check this out this evening.

2022-06-20 22:38 UTC, pH-7 commented on .classpath
> -	<classpathentry kind="src" path="icons"/>
👍

2022-06-20 22:44 UTC, pH-7 commented on src/simplejavatexteditor/SimpleJavaTextEditor.java
> +        //UIMANAGER
I think this comment is quite redundant 🙃  as we can see in the try block we use UIManager (unless you had something else in mind you wanted to let know in the comment..)

2022-06-20 22:44 UTC, pH-7 commented on src/simplejavatexteditor/UI.java
> +    public UI() {
No biggie, just extra spaces here :)

2022-06-21 10:30 UTC, frangametv commented
fixed

2022-06-22 08:20 UTC, pH-7 commented
> fixed

This is brilliant! Amazing job!

2022-06-22 08:20 UTC, pH-7 approved these changes

2022-06-22 08:20 UTC, merged

2022-06-22 08:21 UTC, pH-7 commented
I’ve now merged your changes. Thanks again for your contribution to this project. I really appreciate the improvements you have done to it 👍